# Generated by Django 4.0.4 on 2022-05-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfApp', '0002_category_actor_url_actor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='selfApp.category'),
        ),
    ]
