# Generated by Django 4.0.4 on 2022-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfApp', '0004_alter_actor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
