# Generated by Django 4.0.4 on 2022-06-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfApp', '0007_rename_url_actor_slug_rename_url_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='url',
        ),
    ]
